Expenses/Controllers/CadastroGeralController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Expenses.Controllers
{
    public class CadastroGeralController : Controller
    {
        /*Actions de Forma de Pagamento
        =======================================================================================
        */
        // GET: CadastroGeral
        public ActionResult FormasPagamentoCadastrados()
        {
            FormasPagamentoBLL forma = new FormasPagamentoBLL();
            IList<MLL.FormaPagamento> lista = new List<MLL.FormaPagamento>();

            if (Session["usuarioLogadoID"] == null)
            {
                lista = null;
                Response.Redirect(Url.Action("Index", "Login"));
            }
            else
            {
                lista = forma.ObterListaFormasPag();
            }


            return View(lista);
        }

        public ActionResult CadastrarFormaPagamento()
        {
            return View();
        }

        [HttpPost]
        public string CadastrarFormaPagamento(MLL.FormaPagamento formaPag)
        {
            FormasPagamentoBLL formaBLL = new FormasPagamentoBLL();

            return formaBLL.CadastrarFormaPag(formaPag).ToString();
        }

        [HttpPost]
        public string ExcluirFormaPagamento(int codigo)
        {
            FormasPagamentoBLL formaBLL = new FormasPagamentoBLL();

            MLL.FormaPagamento forma = formaBLL.ObterPorId(codigo);

            return formaBLL.ExcluirFormaPag(forma).ToString();
        }

        public ActionResult EditarFormaPag()
        {
            FormasPagamentoBLL formaBLL = new FormasPagamentoBLL();

            MLL.FormaPagamento forma = formaBLL.ObterPorId(formaBLL.DescriptografaID(Request.QueryString["codigo"]));

            return View(forma);
        }

        [HttpPost]
        public string EditarFormaPag(MLL.FormaPagamento formaPag)
        {
            FormasPagamentoBLL formaBLL = new FormasPagamentoBLL();

            return formaBLL.EditarFormaPag(formaPag).ToString();
        }

        /*Actions de Compras Futuras
       =======================================================================================
       */
        public ActionResult ListaCompras()
        {
            ComprasFuturasBLL comBLL = new ComprasFuturasBLL();

            IList<MLL.CompraFutura> lista = new List<MLL.CompraFutura>();

            if (Session["usuarioLogadoID"] == null)
            {
               Response.Redirect(Url.Action("Index", "Login"));
            }
            else
            {
                ViewBag.listaStatus = comBLL.ObterListaStatus().ToString();
            }

            return View();
        }


        public string ComprasFuturasCadastradasPorUsuario()
        {
            ComprasFuturasBLL comfBLL = new ComprasFuturasBLL();

            return comfBLL.ObterComprasFuturasPorUsuario(Convert.ToInt32(Session["usuariologadoID"])).ToString();  
        }

       
        public ActionResult CadastrarCompraFutura()
        {
            ComprasFuturasBLL comBLL = new ComprasFuturasBLL();

            //Preenchea combo de status
            ViewBag.listaStatus = comBLL.ObterListaStatus().ToString();

            return View();
        }

        [HttpPost]
        public string CadastrarCompraFutura(string obj)
        {
            ComprasFuturasBLL compraBLL = new ComprasFuturasBLL();

            return compraBLL.CadastrarCompraFutura(obj).ToString();
        }

        public ActionResult EditarComprasFuturas()
        {
            ComprasFuturasBLL comBLL = new ComprasFuturasBLL();

            ViewBag.listaStatus = comBLL.ObterListaStatus();

            //MLL.CompraFutura compra = comBLL.ObterPorId();

            return View();
        }

        [HttpPost]
        public string EditarComprasFuturas(string obj)
        {
            ComprasFuturasBLL comBLL = new ComprasFuturasBLL();

            return comBLL.EditarCompraFutura(obj).ToString();
;       }

        [HttpPost]
        public string ExcluirCompraFutura(int codigo)
        {
            ComprasFuturasBLL comBLL = new ComprasFuturasBLL();

            return comBLL.ExcluirCompraFutura(codigo).ToString();
        }

        [HttpPost]
        public string ObterCompra(int codigo)
        {
            ComprasFuturasBLL comBLL = new ComprasFuturasBLL();

            return comBLL.ObterPorId(codigo).ToString();
        } 

        [HttpPost]
        public string ObterProdutosNaCompraDeUsuario()
        {
            ComprasFuturasBLL comBLL = new ComprasFuturasBLL();

            return comBLL.ObterProdutosNaCompraDeUsuario(Convert.ToInt32(Session["usuariologadoId"])).ToString();
        }

    }
}

Expenses/Views/CadastroGeral/CadastrarFormaPagamento.cshtml
@model MLL.FormaPagamento

@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form class="form-horizontal" id="form0" name="form0" method="post">

    <div id="basic-form" class="section">
        <div class="row">
                <div class="card-panel">
                    <h4 class="header2">Cadastro Forma de Pagamento</h4>
                    <div class="row">
                        <form class="col s12">
                            <div class="row">
                                <div class="input-field col s12">
                                    @Html.LabelFor(f => f.Descricao_Forma_Pagamento,new { @class = "validate"})
                                    @Html.EditorFor(f => f.Descricao_Forma_Pagamento,new { @class = "validate", @autofocus = "true"})
                                    @Html.ValidationMessageFor(f => f.Descricao_Forma_Pagamento,null,new { @class = "help-block position-absolute"})
                                </div>
                            </div>
                            <div class="row">
                                <div class="row">
                                    <div class="input-field col s12">
                                        <a id="btSalvar" class="btn waves-effect waves-light right blue" onclick="SaveCustom()">Salvar</a>
                                        &nbsp;<a id="btCancel" class="btn waves-effect waves-light right blue" onclick="CancelCustom()">Cancelar</a> 
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

</form>

<script>
    
    function CancelCustom() {
        swal({
            title: "Deseja cancelar o cadastro?",
            text: "É possível cancelar o cadastramento!!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Sim",
            cancelButtonText: "Não",
            closeOnConfirm: false,
            closeOnCancel: false,

        },
            function (isConfirm) {

                if (isConfirm) {
                    window.location.href = '@Url.Action("FormasPagamentoCadastrados","CadastroGeral")';
                } else {
                    swal("Cancelado", "Cadastramento ainda ativo!!", "error");
                }
            });
    }

    function SaveCustom() {

        $("#form0").validate();

        if ($("#form0").valid()){

            swal({
                title: "Deseja salvar as informações?",
                text: "É possível salvar a forma de pagamento",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Sim",
                cancelButtonText: "Não",
                closeOnConfirm: false,
                closeOnCancel: false,
            },
                function (isConfirm) {

                    var data = $("#form0").serialize();

                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("CadastrarFormaPagamento", "CadastroGeral")',
                            data: data,
                            dataType: 'json',
                            success: function (data) {

                                if (!data.hasOwnProperty("erro")) {
                                    window.location.href = '@Url.Action("FormasPagamentoCadastrados","CadastroGeral")?sucesso=cadastro';
                                } else {
                                    swal("Erro", "Erro ao cadastrar a forma de pagamento", "error");
                                }
                            }

                        });
                    } else {
                        swal("Cancelado", "Cadastro Cancelado", "error");
                    }
                });
        }
        else {
            swal("Alerta", "Revisar campos obrigatórios", "warning");
        }
    }

</script>

Expenses/Views/CadastroGeral/EditarFormaPag.cshtml
@model MLL.FormaPagamento

@{
    ViewBag.Title = "EditarFormaPag";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form class="form-horizontal" id="form0" name="form0" method="post">

    <div id="basic-form" class="section">
        <div class="row">
            <div class="card-panel">
                <h4 class="header2">Editar Forma de Pagamento</h4>
                <div class="row">
                    <form class="col s12">

                        @Html.HiddenFor(f => f.Codigo_Forma_Pagamento)

                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(f => f.Descricao_Forma_Pagamento, new { @class = "validate" })
                                @Html.EditorFor(f => f.Descricao_Forma_Pagamento, new { @class = "validate", @autofocus = "true" })
                                @Html.ValidationMessageFor(f => f.Descricao_Forma_Pagamento, null, new { @class = "help-block position-absolute" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="row">
                                <div class="input-field col s12">
                                    <a id="btSalvar" class="btn waves-effect waves-light right blue" onclick="SaveCustom()">Salvar</a>
                                    &nbsp;<a id="btCancel" class="btn waves-effect waves-light right blue" onclick="CancelCustom()">Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</form>

<script>

 

    function CancelCustom() {

        swal({
            title: "Deseja cancelar a edição?",
            text: "É possível cancelar a edição de um registro!!",
            showCancelButton: true,
            type: "warning",
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Sim",
            cancelButtonText: "Não",
            closeOnConfirm: false,
            closeOnCancel: false,

        },
            function (isConfirm) {

                if (isConfirm) {

                    window.location.href = '@Url.Action("FormasPagamentoCadastrados","CadastroGeral")';

                } else {
                    swal("Cancelado", "Edição cancelada", "error");
                }
            }

        );
    }


    function SaveCustom() {

        $("#form0").validate();

        if ($("#form0").valid()) {

            swal({
                title: "Deseja editar o registro?",
                text: "É possível editar a forma de Pagamento",
                showCancelButton: true,
                type: "warning",
                confirmButtonColor: "#DD6B44",
                confirmButtonText: "Sim",
                cancelButtonText: "Não",
                closeOnConfirm: false,
                closeOnCancel: false,
            },
                function (isConfirm) {

                    if (isConfirm) {

                        var data = $("#form0").serialize();

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("EditarFormaPag","CadastroGeral")',
                            data: data,
                            dataType: "json",
                            success: function (data) {
                                if (!data.hasOwnProperty("erro")) {

                                    window.location.href = '@Url.Action("FormasPagamentoCadastrados","CadastroGeral")?sucesso=edita';
                                } else {
                                    swal("Erro", "Erro ao editar a forma de Pagamento", "error");
                                }
                            }
                        });

                    } else {
                        swal("Cancelado", "Edição cancelada", "error");
                    }
                }

            );

        } else {
            swal("Advertindo", "Revisar campos obrigatórios", "error");
        }

    }
</script>

Expenses/Views/CadastroGeral/FormasPagamentoCadastrados.cshtml
@model IList<MLL.FormaPagamento>

@{
    ViewBag.Title = "Formas Pagamento Cadastrados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="row">
        <div class="card-panel">
            <h4 class="header2">Listagem Formas de Pagamento</h4>
            <br />
            <div class="row">
                <form class="col s12">

                    <a class="btn waves-effect waves-light blue" id="novo" onclick="Novo()">
                        Novo
                        <i class="material-icons right">library_add</i>
                    </a>

                    <div id="data-table-simple_wrapper" class="dataTables_wrapper">

                        <table class="responsive-table display dataTable" id="gridFormasPagamento" role="grid" cellspacing="0" aria-describedby="data-table-simple_info">

                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" aria-controls="data-table-simple" style="width:380px;" aria-sort="ascending" rowspan="1" colspan="1">
                                        Descrição
                                    </th>
                                    <th class="sorting" aria-controls="data-table-simple" style="width:104px;" rowspan="1" colspan="1">
                                        Editar
                                    </th>
                                    <th class="sorting" aria-controls="data-table-simple" style="width:104px;" rowspan="1" colspan="1">
                                        Excluir
                                    </th>
                                </tr>
                            </thead>

                            <tfoot>

                            </tfoot>

                            <tbody>

                                @if (Model.Count != 0)
                                {
                                    foreach (MLL.FormaPagamento forma in Model)
                                    {
                                        <tr class="odd" role="row">
                                            <td class="sorting_1">
                                                @forma.Descricao_Forma_Pagamento
                                            </td>
                                            <td>
                                                <a href="#" onclick='Editar("@Server.UrlEncode(forma.CodigoCript)")' style="color:black;"><i class="material-icons">mode_edit</i></a>
                                            </td>
                                            <td>
                                                <a href="#" onclick='Excluir("@forma.Codigo_Forma_Pagamento")' style="color:black"><i class="material-icons">delete</i></a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>

                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>

    $(document).ready(function () {
        MostrarMensagem();
        $('#gridFormasPagamento').DataTable({
            responsive: true,
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por página",
                "zeroRecord": "Nenhum registro encontrado",
                "info": "Mostrando página _PAGE_ de _PAGES_ <br> Total: _MAX_",
                "infoEmpty": "Não foram encontrados registros",
                "infoFiltered": "(Filtro realizado em _MAX_ total usuários",
                "search": "Pesquisar",
                "oPaginate": {
                    "sFirst": "Primeira página",
                    "sPrevious": "<<",
                    "sNext": ">>",
                    "sLast": "Última página"
                }

            }
        });

    });


    function MostrarMensagem() {
        var msg = '@Html.Raw(Request.QueryString["sucesso"])';


        if (msg == 'cadastro') {
            swal({
                title: "Cadastro",
                text: "Forma de Pagamento cadastrado com sucesso",
                type: "success",
                timer: 4000,
                showConfirmButton: false
            });
        } else if (msg == 'edita') {
            swal({
                title: "Edição",
                text: "Forma de Pagamento atualizado com sucesso",
                type: "success",
                timer: 4000,
                showConfirmButton: false
            });
        } else if (msg == 'exclui') {
            swal({
                title: "Excluir",
                text: "Forma de Pagamento excluído com sucesso",
                type: "success",
                timer: 4000,
                showConfirmButton: false
            });
        }
        
    }


    function Novo() {
        window.location.href = '@Url.Action("CadastrarFormaPagamento","CadastroGeral")';
    }

    function Editar(id) {
        window.location.href = '@Url.Action("EditarFormaPag","CadastroGeral")?codigo=' + id;
    }

    function Excluir(id) {

        swal({
            title: "Deseja excluir a forma de pagamento?",
            text: "É possível excluir a forma de pagamento",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Sim",
            cancelButtonText: "Não",
            closeOnConfirm: false,
            closeOnCancel: false
        },

            function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("ExcluirFormaPagamento","CadastroGeral")',
                        data: {
                            codigo: id
                        },
                        success: function (data) {
                            if (data == "ok") {
                                window.location.href = '@Url.Action("FormasPagamentoCadastrados","CadastroGeral")?sucesso=exclui';
                            } else {
                                swal("Erro", "Erro ao excluir a forma de pagamento", "error");
                            }
                        }
                    });
                }
                else {
                    swal("Cancelado", "Exclusão Cancelada", "error");
                }
            });
    }


</script>