Expenses/Controllers/PerfilController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Expenses.Controllers
{
    public class PerfilController : Controller
    {
        // GET: Perfil
        public ActionResult PerfisCadastrados()
        {
            PerfilBLL perBLL = new PerfilBLL();
            IList<MLL.Perfil> lista = new List<MLL.Perfil>();

            if (Session["usuarioLogadoId"] == null)
            {
                lista = null;
                Response.Redirect(@Url.Action("Index","Login"));
            }
            else
            {
                lista = perBLL.ListaPerfisCadastrados();
            }

            return View(lista);
        }

        public ActionResult CadastrarPerfil()
        {
            return View();
        }

        [HttpPost]
        public string CadastrarPerfil(MLL.Perfil perfil,FormCollection form)
        {
            PerfilBLL perBLL = new PerfilBLL();

            return perBLL.CadastrarPerfil(perfil,form).ToString();
        } 

        [HttpPost]
        public string ExcluirPerfil(int codigo)
        {
            PerfilBLL perBLL = new PerfilBLL();

            MLL.Perfil perfil = perBLL.ObterPorId(codigo);

            return perBLL.ExcluirPerfil(perfil);
        }

        public ActionResult EditarPerfil()
        {
            PerfilBLL perBLL = new PerfilBLL();

            MLL.Perfil perfil = perBLL.ObterPorId(perBLL.DescriptografaID(Request.QueryString["codigo"]));


            return View(perfil);
        }


        [HttpPost]
        public string EditarPerfil(MLL.Perfil perfil,FormCollection form)
        {
            PerfilBLL perBLL = new PerfilBLL();

            return perBLL.EditarPerfil(perfil,form).ToString();
        }
    }
}

Expenses/Controllers/ProdutoController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Expenses.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult ListaProdutos()
        {
            ProdutoBLL proBLL = new ProdutoBLL();

            IList<MLL.Produto> lista = new List<MLL.Produto>();

            if (Session["usuarioLogadoID"] == null)
            {
                Response.Redirect(Url.Action("Index","Login"));
            }
            
            return View();
        }

        public string ProdutosCadastradosPorUsuario()
        {
            ProdutoBLL proBLL = new ProdutoBLL();

            return proBLL.ListaProdutosCadastradosPorUser(Convert.ToInt32(Session["usuarioLogadoID"])).ToString();
        }

        public ActionResult CadastrarProduto()
        {
            return View();
        }

        [HttpPost]
        public string CadastrarProduto(string obj)
        {
            ProdutoBLL proBLL = new ProdutoBLL();

            return proBLL.CadastrarProduto(obj).ToString();
        }

        public ActionResult EditarProduto()
        {
            return View();
        }

        [HttpPost]
        public string EditarProduto(string obj)
        {
            ProdutoBLL proBLL = new ProdutoBLL();

            return proBLL.EditarProduto(obj).ToString();
        }

        [HttpPost]
        public string ExcluirProduto(int codprod)
        {
            ProdutoBLL proBLL = new ProdutoBLL();

            return proBLL.ExcluirProduto(codprod);
        }

        [HttpPost]
        public string ObterProduto(int codigo)
        {
            ProdutoBLL proBLL = new ProdutoBLL();

            return proBLL.ObterPorId(codigo).ToString();
        }

        [HttpPost]
        public string FileUploadImagem()
        {
            HttpPostedFileBase arquivo = Request.Files["file"];

            int codigoproduto = Convert.ToInt32(Request.Form["idproduto"]);

            ProdutoBLL proBLL = new ProdutoBLL();

            var uploadPath = @"~\images\Arquivos_Expenses\";
            var pathRelative = @"\images\Arquivos_Expenses\";
            string caminhoarquivo = Path.Combine(Server.MapPath(@uploadPath + Path.GetFileName(arquivo.FileName)));

            return proBLL.SalvarUploadCompraImagem(arquivo, codigoproduto, arquivo.FileName, caminhoarquivo, pathRelative).ToString();
        }

        [HttpPost]
        public string BuscarCaminhoImagem(int codprod)
        {
            ProdutoBLL proBLL = new ProdutoBLL();

            return proBLL.BuscarCaminhoImagem(codprod).ToString();
        }


    }
}

Expenses/Controllers/UsuariosController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Expenses.Controllers
{
    public class UsuariosController : Controller
    {
        // GET: Usuarios
        public ActionResult UsuariosCadastrados()
        {
            UsuarioBLL usuBLL = new UsuarioBLL();
            IList<MLL.Usuario> lista = new List<MLL.Usuario>();

            if (Session["usuariologadoId"] == null)
            {
                lista = null;
                Response.Redirect(Url.Action("Index","Login"));
            }
            else
            {
                lista = usuBLL.UsuariosCadastrados();
            }

            return View(lista);
        }

        public ActionResult CadastrarUsuario()
        {
            PerfilBLL perBLL = new PerfilBLL();

            ViewBag.listaPerfis = perBLL.ObterListaPerfil();


            return View();
        }

        [HttpPost]
        public string CadastrarUsuario(MLL.Usuario usu,FormCollection form)
        {
            string uploadPath = "";
            string pathRelative = "";
            string caminhoarquivo = "";

            UsuarioBLL usuBLL = new UsuarioBLL();

            //Checagem de upload do arquivo (FOTO)
            HttpPostedFileBase arquivo = null;
            if (Request.Files.Count > 1)
            {
                arquivo = Request.Files[0];

                //Nome e extensão do arquivo
                var img = Path.GetFileName(arquivo.FileName);

                if (ModelState.IsValid)
                {
                    if (arquivo != null && arquivo.ContentLength > 0)
                    {
                        uploadPath = @"~\images\Arquivos_Expenses\Usuarios\";
                        pathRelative = @"\images\Arquivos_Expenses\Usuarios\" + img;
                        caminhoarquivo = Path.Combine(Server.MapPath(@uploadPath + img));
                    }
                }

            }
            return usuBLL.CadastrarUsuario(arquivo,usu,form,caminhoarquivo,pathRelative).ToString();
        }

        public ActionResult EditarUsuario()
        {
            UsuarioBLL usuBLL = new UsuarioBLL();
            MLL.Usuario usuario = usuBLL.ObterPorID(usuBLL.DescriptografaID(Request.QueryString["codigo"]));
            
            PerfilBLL perBLL = new PerfilBLL();

            ViewBag.listaPerfis = perBLL.ObterListaPerfil();

            return View(usuario);
        }

        [HttpPost]
        public string EditarUsuario(MLL.Usuario usu,FormCollection form)
        {
            string uploadPath = "";
            string pathRelative = "";
            string caminhoarquivo = "";

            UsuarioBLL usuBLL = new UsuarioBLL();

           
            //Checagem de upload do arquivo (FOTO)
            HttpPostedFileBase arquivo = null;
            if (Request.Files.Count > 1)
            {
                //No caso de se carregar uma nova imagem faz-se os procedimentos para carregar o arquivo
                //e abastece a propriedade path_Image com um novo carminho relativo com o nome do web server principal
                //no caso NOTE e a aplicação EXPENSES
                arquivo = Request.Files[0];

                //Nome e extensão do arquivo
                var img = Path.GetFileName(arquivo.FileName);

                if (ModelState.IsValid)
                {
                    if (arquivo != null && arquivo.ContentLength > 0)
                    {
                        uploadPath = @"~\images\Arquivos_Expenses\Usuarios\";
                        pathRelative = @"images\Arquivos_Expenses\Usuarios\" + img;
                        caminhoarquivo = Path.Combine(Server.MapPath(@uploadPath + img));
                    }

                    //Caminho com o endereço do Web Server para exibir a foto imagem
                    var pathSalvarNaBase = Path.Combine("http:\\NOTE\\EXPENSES\\" + pathRelative);
                    //Caminho mapeado no servidor fisicamente
                    arquivo.SaveAs(caminhoarquivo);

                    usu.Path_Image = pathSalvarNaBase;
                }

            }
            else
            {
                //O usuário não carregando nenhuma foto nova grava-se o caminho da imagem já cadastrada
                usu.Path_Image = form["txtFileFoto"];
            }

            return usuBLL.EditarUsuario(usu).ToString();
        }

        [HttpPost]
        public string ExcluirUsuario(int codigo)
        {
            UsuarioBLL usuBLL = new UsuarioBLL();

            MLL.Usuario usu = usuBLL.ObterPorID(codigo);

            return usuBLL.ExcluirUsuario(usu);
        }

    }
}

Expenses/Controllers/VigenciaController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Expenses.Controllers
{
    public class VigenciaController : Controller
    {
        public ActionResult ListaVigencia()
        {
            if (Session["usuarioLogadoID"] == null)
            {
                Response.Redirect(Url.Action("Index", "Login"));
            }

            return View();
        }


        // GET: Vigencia
        public ActionResult VigenciasCadastradas()
        {
            //Exemplo utilizando PartialView e objeto ajax
            //if (Request.IsAjaxRequest())
            //{
            //    return PartialView("_ListaVigencia", vigBLL.VigenciasCadastradas(datainicio, datafim));
            //}
            return View();
        }



        [HttpPost]
        public string VigenciasCadastradas(string datainicio = "", string datafim = "")
        {
            VigenciaBLL vigBLL = new VigenciaBLL();

            int codUser = Convert.ToInt32(Session["usuarioLogadoId"]);
            
            return vigBLL.VigenciasCadastradas(datainicio, datafim,codUser).ToString();
        }

        /* Exemplo de retorno JSON
        public ActionResult loaddata(string datainicio = "", string datafim = "")
        {
            VigenciaBLL vigBLL = new VigenciaBLL();

            var data = vigBLL.VigenciasCadastradas(datainicio, datafim).ToList();

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }
        */

        public ActionResult CadastrarVigencia()
        {
            return View();
        }

        [HttpPost]
        public string CadastrarVigencia(MLL.Vigencia vigencia)
        {
            VigenciaBLL vigBLL = new VigenciaBLL();

            vigencia.Codigo_Usuario = Convert.ToInt32(Session["usuarioLogadoId"]);

            return vigBLL.CadastrarVigencia(vigencia).ToString();
        }


        [HttpGet]
        public ActionResult EditarVigencia()
        {
            VigenciaBLL vigBLL = new VigenciaBLL();

            MLL.Vigencia vigencia = vigBLL.ObterPorId(Convert.ToInt32(Request.QueryString["codigo"]));

            DespesaBLL desBLL = new DespesaBLL();
            ViewBag.StatusDespesa = desBLL.ObterStatusDespesa().ToString();
            ViewBag.listaFormaPag = desBLL.ObterFormaPag().ToString();

            return View(vigencia);
        }

        [HttpPost]
        public string EditarVigencia(MLL.Vigencia vigencia)
        {
            VigenciaBLL vigBLL = new VigenciaBLL();

            vigencia.Codigo_Usuario = Convert.ToInt32(Session["usuarioLogadoId"]);

            return vigBLL.EditarVigencia(vigencia).ToString();
        }

        public ActionResult ExcluirVigencia()
        {
            return View();
        }


        [HttpPost]
        public string ExcluirVigencia(int codigo)
        {
            VigenciaBLL vigBLL = new VigenciaBLL();

            MLL.Vigencia vigencia = vigBLL.ObterPorId(codigo);

            return vigBLL.ExcluirVigencia(vigencia);
        }

    }
}

Expenses/Views/Shared/_Layout.cshtml
<html>
<head>
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <title>Control Expenses</title>
    <!-- Favicons-->
    <link rel="icon" href="~/Content/images/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="~/Content/images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="~/Content/images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->
    <!-- CORE CSS-->
    @Styles.Render("~/Content/css/themes/fixed-menu/materialize.css")
    @Styles.Render("~/Content/css/themes/fixed-menu/style.css")
    <!-- Custome CSS-->
    @Styles.Render("~/Content/css/custom/custom.css")
    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    @Styles.Render("~/Content/vendors/perfect-scrollbar/perfect-scrollbar.css")
    @*Styles.Render("~/Content/vendors/data-tables/css/jquery.dataTables.min.css")*@
    @Styles.Render("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css")
    @Styles.Render("https://cdn.datatables.net/select/1.2.7/css/select.dataTables.min.css")

    @Styles.Render("~/Content/vendors/jvectormap/jquery-jvectormap.css")
    @Styles.Render("~/Content/vendors/flag-icon/css/flag-icon.min.css")

    @Styles.Render("~/Content/vendors/noUiSlider/nouislider.css")
    @Styles.Render("~/Content/vendors/prism/prism.css")

    @Styles.Render("~/Content/vendors/sweetalert/dist/sweetalert.css")

    <!-- Para controle fileupload de arrastar e soltar-->
    @Styles.Render("~/Content/vendors/dropify/css/dropify.min.css")

    <!-- para controle de tabs -->
    @Styles.Render("~/Content/css/easy-responsive-tabs.css")

    <!--Scripts-->
    <!--================================================ -->
    @RenderSection("scripts", required: false)

    <!-- jQuery Library -->
    @*Scripts.Render("~/Scripts/jquery-3.2.1.min.js")*@
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")

    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")

    <!-- Para biblioteca de data em português -->
    @Scripts.Render("~/Scripts/methods_pt.js")

    <!-- Para controle fileupload de arrastar e soltar-->
    @Scripts.Render("~/Content/vendors/dropify/js/dropify.min.js")
    @*Scripts.Render("~/Scripts/js/scripts/form-file-uploads.js")*@

    @Scripts.Render("~/Scripts/jquery.maskedinput.min.js")

    <!-- para tabs -->
    @Scripts.Render("~/Scripts/js/easyResponsiveTabs.js")

    <!-- Para exibir checkbox na grid datatable-->
    @Scripts.Render("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js")
    @Scripts.Render("https://cdn.datatables.net/select/1.2.7/js/dataTables.select.min.js")

    <!-- Para ajaxform e progress bar-->
    @Scripts.Render("http://malsup.github.com/jquery.form.js")

    <script>

    </script>

    <style type="text/css" rel="stylesheet">
        body {
            background: #fff;
        }

        #container {
            width: 940px;
            margin: 0 auto;
        }

        @@media only screen and (max-width: 768px) {
            #container {
                width: 90%;
                margin: 0 auto;
            }
        }
    </style>


</head>
<body class="loaded" style="">
    <!-- Start Page Loading -->
    <div id="loader-wrapper">
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>
    <!-- End Page Loading -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START HEADER -->
    <header id="header" class="page-topbar">
        <!-- start header nav-->
        <div class="navbar-fixed">
            <nav class="navbar-color">
                <div class="nav-wrapper">
                    <ul class="left">
                        <li>
                            <h1 class="logo-wrapper">
                                <a href="#" class="brand-logo darken-1">
                                    <img src="~/Content/images/logo/materialize-logo.png" alt="logo">
                                    <span class="logo-text hide-on-med-and-down">Expenses</span>
                                </a>
                            </h1>
                        </li>
                    </ul>
                    
                    <ul class="right hide-on-med-and-down">
                        
                        <li>
                            <a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen">
                                <i class="material-icons">settings_overscan</i>
                            </a>
                        </li>
                        
                        <li>
                            <a href="javascript:void(0);" class="waves-effect waves-block waves-light profile-button" data-activates="profile-dropdown">
                                <span class="avatar-status avatar-online">
                                    <img src="~/Content/images/avatar/avatar-7.png" alt="Foto do Perfil">
                                    <i></i>
                                </span>
                            </a><ul id="profile-dropdown" class="dropdown-content" style="white-space: nowrap; opacity: 1; left: 1156.64px; position: absolute; top: 64px; display: none;">
                                <li>
                                    <a href="#" class="grey-text text-darken-1">
                                        <i class="material-icons">face</i> Profile
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="grey-text text-darken-1">
                                        <i class="material-icons">settings</i> Settings
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="grey-text text-darken-1">
                                        <i class="material-icons">live_help</i> Help
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="grey-text text-darken-1">
                                        <i class="material-icons">lock_outline</i> Lock
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="grey-text text-darken-1">
                                        <i class="material-icons">keyboard_tab</i> Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" data-activates="chat-out" class="waves-effect waves-block waves-light chat-collapse">
                                <i class="material-icons">format_indent_increase</i>
                            </a>
                        </li>
                    </ul>
                    <!-- profile-dropdown -->

                </div>
            </nav>
        </div>
        <!-- end header nav-->
    </header>
    <!-- END HEADER -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START MAIN -->
    <div id="main">
        <!-- START WRAPPER -->
        <div class="wrapper">
            <!-- START LEFT SIDEBAR NAV-->
           
            @Html.Partial("~/Views/Shared/_Menu.cshtml")

            <!-- END LEFT SIDEBAR NAV-->
            <!-- //////////////////////////////////////////////////////////////////////////// -->
            <!-- START CONTENT -->
            <section id="content">
                <!--start container-->
                <div class="container">
                    @RenderBody()
                </div>
                <!--end container-->
            </section>
            <!-- END CONTENT -->
           
        </div>
        <!-- END WRAPPER -->
    </div>
    <!-- END MAIN -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START FOOTER -->
    <footer class="page-footer">
        
        <div class="page-footer">
            <div class="footer-copyright">
                <div class="container">
                    <span>
                        Copyright ©
                        <script type="text/javascript">
                            document.write(new Date().getFullYear());
                        </script><a class="grey-text text-lighten-2" href="http://themeforest.net/user/pixinvent/portfolio?ref=pixinvent" target="_blank">WSF</a> All rights reserved.
                    </span>
                    <span class="right hide-on-small-only"> Design and Developed by <a class="grey-text text-lighten-2" href="#">Wellington Fagundes</a></span>
                </div>
            </div>
        </div>
    </footer>
    <!-- END FOOTER -->
    <!-- ================================================
    Scripts
    ================================================ -->
    <!--materialize js-->
    @Scripts.Render("~/Scripts/js/materialize.min.js")
    <!--prism-->
    @Scripts.Render("~/Content/vendors/prism/prism.js")
    <!--scrollbar-->
    @Scripts.Render("~/Content/vendors/perfect-scrollbar/perfect-scrollbar.min.js")
    <!-- chartjs -->
    @Scripts.Render("~/Content/vendors/chartjs/chart.min.js")
    <!-- sparkline -->
    @Scripts.Render("~/Content/vendors/sparkline/jquery.sparkline.min.js")
    <!--jvectormap-->
    @Scripts.Render("~/Content/vendors/jvectormap/jquery-jvectormap-1.2.2.min.js")
    @Scripts.Render("~/Content/vendors/jvectormap/jquery-jvectormap-world-mill-en.js")
    @Scripts.Render("~/Content/vendors/jvectormap/vectormap-script.js")

    <!-- data-tables -->
    @Scripts.Render("~/Scripts/vendors/data-tables/js/jquery.dataTables.min.js")
    
    <!--angularjs-->
    @Scripts.Render("~/Scripts/vendors/angular.min.js")

    <!--sweetalert -->
    @Scripts.Render("~/Scripts/vendors/sweetalert/dist/sweetalert.min.js")

    <div class="jvectormap-label"></div>
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    @Scripts.Render("~/Scripts/js/plugins.js")
    <!-- Modal -->
    @Scripts.Render("~/Scripts/js/advanced-ui-modals.js")
    <!--custom-script.js - Add your own theme custom JS-->
    @Scripts.Render("~/Scripts/js/custom-script.js")

    <div class="hiddendiv common"></div><div class="drag-target" data-sidenav="slide-out" style="left: 0px; touch-action: pan-y; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></div><div class="drag-target" data-sidenav="chat-out" style="touch-action: pan-y; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); right: 0px;"></div>
</body>
</html>

Expenses/Views/Shared/_Menu.cshtml
@{ 


}


<aside id="left-sidebar-nav">
    <ul id="slide-out" class="side-nav fixed leftside-navigation ps-container ps-active-y" style="transform: translateX(-100%);">
        <li class="user-details cyan darken-2">
            <div class="row">
                <div class="col col s4 m4 l4">
                    <img src="~/Content/images/avatar/avatar-7.png" alt="" class="circle responsive-img valign profile-image cyan">
                </div>
                <div class="col col s8 m8 l8">

                    <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown-nav">John Doe<i class="mdi-navigation-arrow-drop-down right"></i></a><ul id="profile-dropdown-nav" class="dropdown-content" style="white-space: nowrap; position: absolute; top: 59px; left: 101.234px; display: none; opacity: 1;">
                        <li>
                            <a href="#" class="grey-text text-darken-1">
                                <i class="material-icons">face</i> Profile
                            </a>
                        </li>
                        <li>
                            <a href="#" class="grey-text text-darken-1">
                                <i class="material-icons">settings</i> Settings
                            </a>
                        </li>
                        <li>
                            <a href="#" class="grey-text text-darken-1">
                                <i class="material-icons">live_help</i> Help
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#" class="grey-text text-darken-1">
                                <i class="material-icons">lock_outline</i> Lock
                            </a>
                        </li>
                        <li>
                            <a href="#" class="grey-text text-darken-1">
                                <i class="material-icons">keyboard_tab</i> Logout
                            </a>
                        </li>
                    </ul>
                    <p class="user-roal">Administrator</p>
                </div>
            </div>
        </li>

        <!-- Menus -->

        <li class="no-padding">
            <ul class="collapsible" data-collapsible="accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="material-icons">dvr</i>
                        <span class="nav-text">Cadastro Gerais</span>
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="@Url.Action("FormasPagamentoCadastrados","CadastroGeral")">
                                    <i class="material-icons">keyboard_arrow_right</i>
                                    <span>Forma de Pagamento</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("ListaProdutos","Produto")">
                                    <i class="material-icons">keyboard_arrow_right</i>
                                    <span>Produtos</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("ListaCompras","CadastroGeral")">
                                    <i class="material-icons">keyboard_arrow_right</i>
                                    <span>Compras Futuras</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                @{
                    BLL.PerfilBLL perfil = new BLL.PerfilBLL();
                    if (perfil.ExibirMenuPerfilAdm(Session["emailUsuarioLogado"].ToString()))
                    {
                        <li class="bold">
                            <a href="@Url.Action("PerfisCadastrados","Perfil")" class="collapsible-header waves-effect waves-cyan">
                                <i class="material-icons">web</i>
                                <span class="nav-text">Perfil</span>
                            </a>
                        </li>

                        <li class="bold">
                            <a href="@Url.Action("UsuariosCadastrados","Usuarios")" class="collapsible-header waves-effect waves-cyan">
                                <i class="material-icons">cast</i>
                                <span class="nav-text">Usuários</span>
                            </a>
                        </li>

                        <li class="bold">
                            <a href="@Url.Action("#","#")" class="collapsible-header waves-effect waves-cyan">
                                <i class="material-icons">cast</i>
                                <span class="nav-text">Permissões</span>
                            </a>
                        </li>
                    }
                }

                <li class="bold">
                    <a href="@Url.Action("ListaVigencia","Vigencia")" class="collapsible-header waves-effect waves-cyan">
                        <i class="material-icons">mail_outline</i>
                        <span class="nav-text">Vigência</span>
                    </a>
                </li>

            </ul>
        </li>
       


        <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" style="left: 0px; width: 0px;"></div></div>
        <div class="ps-scrollbar-y-rail" style="top: 0px; height: 528px; right: 3px;"><div class="ps-scrollbar-y" style="top: 0px; height: 201px;"></div></div>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only">
        <i class="material-icons">menu</i>
    </a>
</aside>